# Minimal CI to see the output
name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*"

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        lua-version: ["5.3", "5.4"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: leafo/gh-actions-luarocks@v4

      - name: build
        run: |
          luarocks install busted
          luarocks make

      - name: test
        run: |
          busted -o codewars || true
